workflow:
    rules:
        - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event" 
          when: never
        - when: always
variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
stages:
    - test
    - build
    - deploy_dev
    - deploy_staging
    - deploy_prod
run_unit_tests:
    image: node:20-alpine
    stage: test
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - node_modules
    tags:
        - remote
    before_script:
        - echo "begin test"
        - npm install  
    script:
        - echo "running tests!....."
run_lint_checks:
    image: node:20-alpine
    stage: test
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - node_modules
        policy: pull
    tags:
        - remote
    before_script:
        - npm install
    script:
        - echo "Running lint checks"    

sast:
    stage: test


build_image:
    stage: build
    tags:
        - digital
    before_script:
        - export PACKAGE_JSON_VERSION=$(cat package.json | jq -r .version)
        - export VERSION=$PACKAGE_JSON_VERSION.$CI_PIPELINE_IID
        - echo "VERSION=$VERSION" >> build.env

    script:
        - docker build -t $IMAGE_NAME:$VERSION .
    artifacts:
        reports:
            dotenv: build.env
         

push_iamge:
    stage: build
    needs:
        - build_image
    tags:
        - ocean
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY    
    script:
        - docker push $IMAGE_NAME:$VERSION

.deploy:
    tags:
        - digital
    variables:
        APP_PORT: ""
        DEPLOY_ENV: ""     
    before_script:
        - chmod 400 $SSH_PRIVATE_KEY   
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ./docker-compose.yaml root@159.223.203.142:/root/back
        - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@159.223.203.142 "
            cd back &&
            docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
            export COMPOSE_PROJECT_NAME=back-$DEPLOY_ENV &&
            export DC_BACK_IMAGE_NAME=$IMAGE_NAME &&
            export DC_BACK_IMAGE_TAG=$VERSION &&
            export DC_BACK_APP_PORT=$APP_PORT &&
            docker compose -f docker-compose.yaml down &&
            docker compose -f docker-compose.yaml up -d"            



deploy_to_staging:
    extends: .deploy
    stage: deploy_dev
    variables:
        APP_PORT: 3003
        DEPLOY_ENV: dev 

deploy_to_production:
    extends: .deploy
    stage: deploy_prod
    variables:
        APP_PORT: 5005
        DEPLOY_ENV: production
    when: manual    

run_performance_tests:
    stage: deploy_prod
    needs:
        - deploy_to_production
    script:
        - echo "running performace tests."    


include:
    - template: Jobs/SAST.gitlab-ci.yml

